# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
  ldflags:
  - -X "github.com/lhopki01/git-mass-sync/cmd.Version={{.Env.VERSION}}"
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
  - github:
      owner: lhopki01
      name: brew
    commit_author:
      name: lhopki01
      email: lhopki01@gmail.com
    dependencies:
      - git
      - hub
    description: "Tool to keep multiple local repos in sync with github"
    folder:
      - Formula
    install: |
      bin.install "git-mass-sync"

