# This file was generated by GoReleaser. DO NOT EDIT.
class GitMassSync < Formula
  desc ""
  homepage ""
  version "2.0.0"

  if OS.mac?
    url "https://github.com/lhopki01/git-mass-sync/releases/download/v2.0.0/git-mass-sync_2.0.0_Darwin_x86_64.tar.gz"
    sha256 "b6342c74944bd11b08b6c140670a0a2609ba89c54c6d6ad9b613ef0aef98d204"
  elsif OS.linux?
    url "https://github.com/lhopki01/git-mass-sync/releases/download/v2.0.0/git-mass-sync_2.0.0_Linux_x86_64.tar.gz"
    sha256 "bee953d1bb851e99b73526849981624fbd250d15cae956cd9c7e4092c6346720"
  end
  
  depends_on "git"
  depends_on "hub"

  def install
    bin.install "git-mass-sync"
  end
end
