# This file was generated by GoReleaser. DO NOT EDIT.
class GitMassSync < Formula
  desc ""
  homepage ""
  url "https://github.com/lhopki01/git-mass-sync/releases/download/v0.1.3/git-mass-sync_0.1.3_Darwin_x86_64.tar.gz"
  version "0.1.3"
  sha256 "7b24b9ff78916e86effd3d9bde477b8edabc304fa07eccb5fabe17f044e3074a"
  
  depends_on "git"
  depends_on "hub"

  def install
    bin.install "git-mass-sync"
  end
end
